services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app'
    volumes: 
    - .:/app
    ports:
      - 8080:8080

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # host:container → doğru eşleştirme
    environment:
      POSTGRES_USER: "fast_api_user"
      POSTGRES_PASSWORD: "fast_api_password"
      POSTGRES_DB: "fast_api_db"

volumes:
  postgres_data: